general {
    recording = [
        ./,
        ./models
    ]
    
}

dir_path {
    data_dir = ./data/
    result_dir = ./result/
    ckpt_dir = ./ckpt/
    # dataset_dir = SIGA_batch_1
}

train {
    learning_rate = 0.0001
    max_iter = 40000
    max_iter_2 = 60000
    warm_up_end = 1000
    outlier = 0.002
    extra_points_rate = 1
    low_range = 1.1

    batch_size = 20000
    batch_size_step2 = 40000

    save_freq = 10000
    val_freq = 10000
    val_mesh_freq = 10000
    resolution = 256
    threshold = 0.01
    report_freq = 10000

    igr_weight = 0.1
    mask_weight = 0.0
    load_ckpt = none
}
evaluate {
    load_ckpt = ckpt_080000.pth
    use_vectorAdam = 1
    iter_1st = 100
    iter_2nd = 300
    iter_max = 250
    normal_step = 300
    report_freq = 100
    max_batch = 400000
    export_grad_field = 0
    laplacian_weight = 2000
    save_iter = 100
    learning_rate = 0.05
    warm_up_end = 20
    resolution = 256
    threshold = 0.005
    use_exist_mesh = 0
    draw_slice = 0
    is_cut = 1
    region_rate = 20
    watertight_separate = 1
    sample_batch_size = 10000000
}
model {
    udf_network {
        d_in = 3,
    	d_out = 1,
        d_hidden = 256,
        n_layers = 8,
        skip_in = [4],
        multires = 0,
        bias = 0.5,
        scale = 1.0,
        geometric_init = True,
        weight_norm = True
    }

}
